version: "3"

services:
    express-app-server:
        build: .
        ports:
            - "3000:3000"
        environment:
            - DATABASE_URL=mysql://root:samurai@mysql-db-server:3306/code_samurai_2024?schema=public
            - PORT=3000
        depends_on:
            - mysql-db-server

    mysql-db-server:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: samurai
            MYSQL_DATABASE: code_samurai_2024
        # volumes:
        #     - db-store:/var/lib/mysql

volumes:
    db-store:
